#!/usr/bin/env bash
# Script that installs nginx on your web-01 and server
sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
