#!/usr/bin/env bash
# Script that installs nginx on your web-01 and server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
sudo service nginx reload
#sudo systemctl restart nginx
