#!/usr/bin/env bash
# Script that configures Nginx server with a custom header
sudo apt-get update
sudo apt-get -y install nginx
sudo service nginx start
#echo "Hello World!" > /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
err_page="\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;$err_page\n\tadd_header X-Served-By $HOSTNAME;" /etc/nginx/sites-available/default
#sudo sed -i "$err_page" /etc/nginx/sites-available/default
#sudo sed -i 'X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default
sudo service nginx restart
