#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*
#config_loadbal="frontend bind *:80 mode http default_backend lb-webapp backend lb-webapp balance roundrobin server 188140-web-01 54.85.96.179:80 check server 188140-web-02 34.232.65.41:80 check"
#echo "$config_loadbal" >> /etc/haproxy/haproxy.cfg
echo -e "\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 188140-web-01 54.85.96.179:80 check\n\tserver 188140-web-02 34.232.65.41:80 check" >> /etc/haproxy/haproxy.cfg
sudo cp -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
