#!/usr/bin/env bash
# Install and configure HAproxy
sudo apt-get -y update
# sudo apt-get -y install software-properties-common
# sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
# sudo apt-get -y update
sudo apt-get -y install haproxy
#config_loadbal="frontend bind *:80 mode http default_backend lb-webapp backend lb-webapp balance roundrobin server 188140-web-01 54.85.96.179:80 check server 188140-web-02 34.232.65.41:80 check"
#echo "$config_loadbal" >> /etc/haproxy/haproxy.cfg
server_config=\
"
frontend  samuel-frontend
        bind *:80
        mode http
        default_backend samuel-backend
backend samuel-backend
        balance roundrobin
        server 188140-web-01 54.85.96.179:80 check
        server 188140-web-02 34.232.65.41:80 check
"
echo "$server_config" | sudo tee --append /etc/haproxy/haproxy.cfg
#sudo cp -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
