#!/usr/bin/env bash
# that generates a MySQL dump and creates a compressed archive out of it.
sudo mysqldump -uroot -p"$1" --all-databases > backup.sql
tar -czvf "$(date '+%d-%m-%Y').tar.gz" backup.sql
