#!/usr/bin/env bash
# Prints some messages according to sended signals
file="/var/run/myscript.pid"
echo $$ > $file
trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT
while true;
do
	echo "To infinity and beyond"
done
