#!/usr/bin/env bash
# Displays the fizzbuzz sequence
x=1;
while [ $x -le 100 ];
do
	if [ $(( x % 15 )) -eq 0 ];
	then
		echo "FizzBuzz"
	elif [ $(( x % 5 )) -eq 0 ];
	then
		echo "Buzz"
	elif [ $(( x % 3 )) -eq 0 ];
	then
		echo "Fizz"
	else
		echo "$x"
	fi
	(( x++ ));
done
