#!/usr/bin/env bash
# script that loops from 1 to 10 and:
#   displays bad luck for the 4th loop iteration
#   displays good luck for the 8th loop iteration
#   displays Best School for the other iterations
x=1;
while [ $x -le 20 ];
do
	case "$x" in
		5) echo "bad luck from China" ;;
		10) echo "bad luck from Japan" ;;
		18) echo "bad luck from Italy" ;;
	esac
	echo "$x"
	(( x++ ));
done
