#!/usr/bin/env bash
# Bash script that configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/localhost/127.0.0.2/' ~/hosts.new
sed -i '3a8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
